#!/bin/bash
kubectl apply -f `pwd`/reconciliation-engine/target/manifests/k8s/reconciliation-engine/nats-deployment.yml
kubectl apply -f `pwd`/reconciliation-engine/target/manifests/k8s/reconciliation-engine/configMap_k8s.yml
kubectl apply -f `pwd`/reconciliation-engine/target/manifests/k8s/reconciliation-engine/service-deployment_k8s.yml