apiVersion: v1
kind: Service
metadata:
  name: reconciliation-engine
  labels:
    app: reconciliation-engine
spec:
  ports:
    - port: 18080
      protocol: TCP
      targetPort: 18080
  selector:
    app: reconciliation-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-engine
spec:
  selector:
    matchLabels:
      app: reconciliation-engine
  replicas: 1
  template:
    metadata:
      labels:
        app: reconciliation-engine
    spec:
      containers:
        - name: reconciliation-engine
          image: docker.io/saiprasadkrishnamurthy/reconciliation-engine:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: reconciliation-engine-0.0.1-snapshot
          ports:
            - containerPort: 18080

