apiVersion: v1
kind: ConfigMap
metadata:
  name: "reconciliation-engine-ui-0.0.1-snapshot"
  namespace: default
data:
  nats_server: "nats://nats:4222"
  artifactId: "reconciliation-engine-ui"
  random: "a747b4e2-db21-4919-8fb6-53df32cd43b7"
  version: "0.0.1-SNAPSHOT"
  gitVersion: "53092650a81de0d5cee06308fab5cbaf50456658"
  configMapTemplateName: "reconciliation-engine-ui-0.0.1-snapshot"
  imageName: "docker.io/saiprasadkrishnamurthy/reconciliation-engine-ui"
  replicas: "1"
  minReadySeconds: "60"
  server_servlet_contextpath: "/reconciliation-engine-ui"
  server_port: "28080"
  reconTriggerSubject: "dev2.reconciliation.trigger.main"
  spring_data_mongodb_database: "taxreco"
  serviceName: "reconciliation-engine-ui"
  spring_data_mongodb_uri: "mongodb+srv://sai:sai@cluster1.khkphay.mongodb.net/?retryWrites=true&w=majority"
  reconStreamName: "dev2_recon_consumer_stream"

