apiVersion: v1
kind: ConfigMap
metadata:
  name: "reconciliation-engine-ui-0.0.1-snapshot"
  namespace: default
data:
  nats_server: "nats://nats:4222"
  artifactId: "reconciliation-engine-ui"
  random: "38d87de6-ddde-40c6-ae9d-c8fda8e49a81"
  version: "0.0.1-SNAPSHOT"
  gitVersion: "162202fcb0ba8246932bd27006b08ea34707b7e7"
  configMapTemplateName: "reconciliation-engine-ui-0.0.1-snapshot"
  imageName: "docker.io/saiprasadkrishnamurthy/reconciliation-engine-ui"
  replicas: "1"
  minReadySeconds: "60"
  server_servlet_contextpath: "/reconciliation-engine-ui"
  server_port: "28080"
  reconTriggerSubject: "dev2.reconciliation.trigger.main"
  spring_data_mongodb_database: "taxreco"
  serviceName: "reconciliation-engine-ui"
  spring_data_mongodb_uri: "mongodb+srv://sai:sai@cluster1.khkphay.mongodb.net/?retryWrites=true&w=majority"
  reconStreamName: "dev2_recon_consumer_stream"

