apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  labels:
    app: ingest-service
spec:
  type: NodePort
  ports:
    - port: 38080
      protocol: TCP
      targetPort: 38080
  selector:
    app: ingest-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
spec:
  selector:
    matchLabels:
      app: ingest-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ingest-service
    spec:
      containers:
        - name: ingest-service
          image: docker.io/saiprasadkrishnamurthy/ingest-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ingest-service-0.0.1-snapshot
          ports:
            - containerPort: 38080

